# Generated by Django 3.2.7 on 2021-10-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.CharField(default='Furniture', max_length=50),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
